# -*- coding: utf-8 -*-
"""Frame-To-Video.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lpn3Bo8dSoz1JbhCty2KRMH4vEcUlPgK
"""

pip install opencv-python

import cv2
import os

def frames_to_video(input_path, output_path, fps):
    image_array = []
    files = [f for f in os.listdir(input_path) if os.path.isfile(os.path.join(input_path, f))]
    files.sort()  # Sort the files in alphabetical order, ensure they are in the correct sequence

    for i, filename in enumerate(files):
        img = cv2.imread(os.path.join(input_path, filename))
        if img is None:
            continue
        height, width, layers = img.shape
        size = (width, height)
        img = cv2.resize(img, size)
        image_array.append(img)

    # Define the codec and create VideoWriter object
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')  # 'mp4v' is the codec for .mp4 format
    out = cv2.VideoWriter(output_path, fourcc, fps, size)

    for i in range(len(image_array)):
        out.write(image_array[i])  # Write out frame to video

    out.release()

# Define the path to your frames and the output video file
input_path = 'path/to/your/frames'
output_path = 'path/to/output/video.mp4'
fps = 24  # Frames per second

frames_to_video(input_path, output_path, fps)